language: cpp
sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - make
      - g++-4.8
      - libsword-dev
      - libreadline-dev
      - libboost-program-options-dev

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script:
  - mkdir -p tests/build
  - mkdir -p build
  - cd tests/build
  - cmake ../
  - make
  #- ./cbibleTests
  - cd ../../build
  - cmake ../
  - make
