language: cpp
sudo: required

services:
  - docker

before_install:
  - docker build -t timotheosh/cbible-tests ${TRAVIS_BUILD_DIR}/tests/docker

compiler:
  - gcc

script:
  - docker run -v ${TRAVIS_BUILD_DIR}:/usr/local/src -t timotheosh/cbible-tests /bin/bash -c /usr/local/src/tests/run_tests.sh
