language: C++
sudo: false
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libsword-dev
      - libreadline-dev
      - libboost-program-options-dev
      - cmake
      - make
before_script:
  - mkdir build
  - cd build
  - cmake ../

script: make