language: cpp
sudo: required

services:
  - docker

before_install:
  - cd cbible/tests/docker
  - docker build -t timotheosh/cbible-tests

compiler:
  - gcc

script:
  - docker run -v ~/cbible:/usr/local/src -v ~/cbible/tests/swordtest:/usr/share/sword/modules -t timotheosh/cbible-tests /bin/bash -c /usr/local/src/tests/run_tests.sh
